export const FORM_TYPES = [
  'Vehicle Inspection',
  'TBT (Toolbox Talk)',
  'Tools Inspection',
  'PPE Inspection',
  'Quality Check on Field',
  'Incident Report',
  'Violence Report',
]

const yesNo = ['Yes', 'No']
const okNotOk = ['OK', 'Not OK']

export const HSE_FORM_SCHEMAS = {
  'Vehicle Inspection': [
    { key: 'inspectionDateTime', label: 'Inspection Date & Time', type: 'datetime-local' },
    { key: 'location', label: 'Location', type: 'text' },
    { key: 'department', label: 'Department', type: 'select', options: ['Water', 'Electrical'] },
    { key: 'driverNameAndId', label: 'Driver Name & ID', type: 'text' },
    { key: 'ropMulkia', label: 'ROP Mulkia', type: 'text' },
    { key: 'licenseExpiry', label: 'License Expiry', type: 'date' },
    { key: 'registrationNo', label: 'Registration No.', type: 'text' },
    { key: 'vehicleNumber', label: 'Vehicle Number', type: 'text' },
    { key: 'typeOfVehicle', label: 'Type of Vehicle', type: 'text' },
    { key: 'odometerReading', label: 'Odometer Reading', type: 'text' },
    { key: 'fuelLevel', label: 'Fuel Level', type: 'text' },
    { key: 'fuelCard', label: 'Fuel Card', type: 'text' },
    { key: 'tyreCondition', label: 'Tyre Condition', type: 'select', options: okNotOk },
    { key: 'brakesCheck', label: 'Brakes Check', type: 'select', options: okNotOk },
    { key: 'lightsIndicators', label: 'Lights/Indicators', type: 'select', options: okNotOk },
    { key: 'hornAndReverseAlarm', label: 'Horn & Reverse Alarm', type: 'select', options: okNotOk },
    { key: 'mirrorCondition', label: 'Mirror Condition', type: 'select', options: okNotOk },
    { key: 'windShieldCondition', label: 'Wind Shield Condition', type: 'select', options: okNotOk },
    { key: 'wipersWorking', label: 'Wipers Working', type: 'select', options: okNotOk },
    { key: 'spareTireAvailable', label: 'Spare Tire Available', type: 'select', options: yesNo },
    { key: 'numberPlateVisible', label: 'Number Plate Visible', type: 'select', options: yesNo },
    { key: 'seatBeltsWorking', label: 'Seat Belts Working', type: 'select', options: yesNo },
    { key: 'dashboardWarningLights', label: 'Dashboard Warning Lights', type: 'text' },
    { key: 'acWorking', label: 'AC Working', type: 'select', options: yesNo },
    { key: 'fireExtinguisherAvailable', label: 'Fire Extinguisher Available', type: 'select', options: yesNo },
    { key: 'firstAidKitAvailable', label: 'First Aid Kit Available', type: 'select', options: yesNo },
    { key: 'insuranceAndRegistrationValidity', label: 'Insurance & Registration Validity', type: 'text' },
    { key: 'overallVehicleCondition', label: 'Overall Vehicle Condition', type: 'text' },
    { key: 'issuesFound', label: 'Issues Found', type: 'textarea' },
    { key: 'photoUpload', label: 'Photo Upload (URL)', type: 'text' },
    { key: 'inspectorNameAndSignature', label: 'Inspector Name & Signature', type: 'text' },
  ],
  'TBT (Toolbox Talk)': [
    { key: 'dateTime', label: 'Date & Time', type: 'datetime-local' },
    { key: 'locationOrSite', label: 'Location / Site', type: 'text' },
    { key: 'department', label: 'Department', type: 'text' },
    { key: 'tbtTopic', label: 'TBT Topic', type: 'text' },
    { key: 'descriptionOrInstructionsGiven', label: 'Description / Instructions Given', type: 'textarea' },
    { key: 'supervisorConductingTbt', label: 'Supervisor Conducting TBT', type: 'text' },
    { key: 'teamMembersPresent', label: 'Team Members Present (comma separated)', type: 'list' },
    { key: 'teamMembersAbsent', label: 'Team Members Absent', type: 'text' },
    { key: 'safetyRisksDiscussed', label: 'Safety Risks Discussed', type: 'textarea' },
    { key: 'preventiveMeasures', label: 'Preventive Measures', type: 'textarea' },
    { key: 'remarks', label: 'Remarks', type: 'textarea' },
    { key: 'photoUpload', label: 'Photo Upload (URL)', type: 'text' },
    { key: 'supervisorSignature', label: 'Supervisor Signature', type: 'text' },
  ],
  'Tools Inspection': [
    { key: 'dateTime', label: 'Date & Time', type: 'datetime-local' },
    { key: 'siteOrLocation', label: 'Site / Location', type: 'text' },
    { key: 'department', label: 'Department', type: 'text' },
    { key: 'inspectorName', label: 'Inspector Name', type: 'text' },
    { key: 'toolCategory', label: 'Tool Category', type: 'text' },
    { key: 'toolName', label: 'Tool Name', type: 'text' },
    { key: 'toolIdOrSerialNumber', label: 'Tool ID/Serial Number', type: 'text' },
    { key: 'physicalCondition', label: 'Physical Condition', type: 'select', options: ['Good', 'Damaged'] },
    { key: 'calibrationRequired', label: 'Calibration Required', type: 'select', options: yesNo },
    { key: 'safeToUse', label: 'Safe to Use', type: 'select', options: yesNo },
    { key: 'issuesFound', label: 'Issues Found', type: 'textarea' },
    { key: 'actionRequired', label: 'Action Required', type: 'textarea' },
    { key: 'photoUpload', label: 'Photo Upload (URL)', type: 'text' },
    { key: 'inspectorSignature', label: 'Inspector Signature', type: 'text' },
  ],
  'PPE Inspection': [
    { key: 'dateTime', label: 'Date & Time', type: 'datetime-local' },
    { key: 'siteOrLocation', label: 'Site / Location', type: 'text' },
    { key: 'department', label: 'Department', type: 'text' },
    { key: 'supervisorName', label: 'Supervisor Name', type: 'text' },
    { key: 'employeeNameOrId', label: 'Employee Name/ID', type: 'text' },
    { key: 'ppeChecklist', label: 'PPE Checklist (comma separated)', type: 'list' },
    { key: 'ppeCondition', label: 'PPE Condition', type: 'select', options: ['Good', 'Damaged', 'Missing'] },
    { key: 'wearingProperly', label: 'Wearing Properly', type: 'select', options: yesNo },
    { key: 'expiryDateCheck', label: 'Expiry Date Check', type: 'date' },
    { key: 'nonComplianceDetails', label: 'Non-compliance Details', type: 'textarea' },
    { key: 'employeeDetails', label: 'Employee Details', type: 'textarea' },
    { key: 'correctiveActionTaken', label: 'Corrective Action Taken', type: 'textarea' },
    { key: 'photoUpload', label: 'Photo Upload (URL)', type: 'text' },
    { key: 'signature', label: 'Signature', type: 'text' },
  ],
  'Quality Check on Field': [
    { key: 'dateTime', label: 'Date & Time', type: 'datetime-local' },
    { key: 'siteLocation', label: 'Site Location', type: 'text' },
    { key: 'department', label: 'Department', type: 'select', options: ['Water', 'Electrical'] },
    { key: 'workType', label: 'Work Type', type: 'text' },
    { key: 'teamName', label: 'Team Name', type: 'text' },
    { key: 'qualityChecklist', label: 'Quality Checklist (comma separated)', type: 'list' },
    { key: 'workAsPerStandard', label: 'Work as per Standard', type: 'select', options: yesNo },
    { key: 'issuesFound', label: 'Issues Found', type: 'textarea' },
    { key: 'reworkRequired', label: 'Rework Required', type: 'select', options: yesNo },
    { key: 'remarks', label: 'Remarks', type: 'textarea' },
    { key: 'photoUpload', label: 'Photo Upload (URL)', type: 'text' },
    { key: 'inspectorSignature', label: 'Inspector Signature', type: 'text' },
  ],
  'Incident Report': [
    { key: 'incidentDateTime', label: 'Incident Date & Time', type: 'datetime-local' },
    { key: 'location', label: 'Location', type: 'text' },
    { key: 'department', label: 'Department', type: 'text' },
    { key: 'reportedBy', label: 'Reported By', type: 'text' },
    { key: 'incidentType', label: 'Incident Type', type: 'text' },
    { key: 'descriptionOfIncident', label: 'Description of Incident', type: 'textarea' },
    { key: 'personsInvolved', label: 'Persons Involved', type: 'textarea' },
    { key: 'injuryDetails', label: 'Injury Details', type: 'textarea' },
    { key: 'immediateActionTaken', label: 'Immediate Action Taken', type: 'textarea' },
    { key: 'rootCauseIfKnown', label: 'Root Cause (if known)', type: 'textarea' },
    { key: 'preventiveAction', label: 'Preventive Action', type: 'textarea' },
    { key: 'photoUpload', label: 'Photo Upload (URL)', type: 'text' },
    { key: 'supervisorOrManagerReview', label: 'Supervisor/Manager Review', type: 'textarea' },
    { key: 'signature', label: 'Signature', type: 'text' },
  ],
  'Violence Report': [
    { key: 'dateTime', label: 'Date & Time', type: 'datetime-local' },
    { key: 'location', label: 'Location', type: 'text' },
    { key: 'reportedBy', label: 'Reported By', type: 'text' },
    { key: 'personsInvolved', label: 'Person(s) Involved', type: 'textarea' },
    { key: 'type', label: 'Type', type: 'select', options: ['Verbal', 'Physical', 'Threat'] },
    { key: 'descriptionOfIncident', label: 'Description of Incident', type: 'textarea' },
    { key: 'witnessDetails', label: 'Witness Details', type: 'textarea' },
    { key: 'immediateActionTaken', label: 'Immediate Action Taken', type: 'textarea' },
    { key: 'severityLevel', label: 'Severity Level', type: 'text' },
    { key: 'policeOrManagementInformed', label: 'Police/Management Informed', type: 'select', options: yesNo },
    { key: 'remarks', label: 'Remarks', type: 'textarea' },
    { key: 'signature', label: 'Signature', type: 'text' },
  ],
}
